// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAILa4nGgf9cFTB1CYU-4KewxsmMLlhOZc',
    appId: '1:690492748287:web:1e92eb0b9ee31cc3eaf7ca',
    messagingSenderId: '690492748287',
    projectId: 'smartshop-abc02',
    authDomain: 'smartshop-abc02.firebaseapp.com',
    storageBucket: 'smartshop-abc02.firebasestorage.app',
    measurementId: 'G-2WSK0PXXW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGLUPAZVwSh-P999zQujY6C0mALqmLbYQ',
    appId: '1:690492748287:android:34f00b5d5a210baceaf7ca',
    messagingSenderId: '690492748287',
    projectId: 'smartshop-abc02',
    storageBucket: 'smartshop-abc02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFUZOqFssp6yGKJOkRYsXpo1xzWaPEt_I',
    appId: '1:690492748287:ios:d6e7c3c09ed69251eaf7ca',
    messagingSenderId: '690492748287',
    projectId: 'smartshop-abc02',
    storageBucket: 'smartshop-abc02.firebasestorage.app',
    iosBundleId: 'com.example.smartshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFUZOqFssp6yGKJOkRYsXpo1xzWaPEt_I',
    appId: '1:690492748287:ios:d6e7c3c09ed69251eaf7ca',
    messagingSenderId: '690492748287',
    projectId: 'smartshop-abc02',
    storageBucket: 'smartshop-abc02.firebasestorage.app',
    iosBundleId: 'com.example.smartshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAILa4nGgf9cFTB1CYU-4KewxsmMLlhOZc',
    appId: '1:690492748287:web:f233ab1024ba2e5eeaf7ca',
    messagingSenderId: '690492748287',
    projectId: 'smartshop-abc02',
    authDomain: 'smartshop-abc02.firebaseapp.com',
    storageBucket: 'smartshop-abc02.firebasestorage.app',
    measurementId: 'G-7T107E82YE',
  );
}
